apiVersion: v1
kind: ConfigMap
metadata:
  name: $APP_INSTANCE_NAME-alertmanager-config
  labels:
    app.kubernetes.io/name: $APP_INSTANCE_NAME
    app.kubernetes.io/component: alertmanager
data:
  # To learn more: https://prometheus.io/docs/alerting/configuration/
  alertmanager.yml: |
    global: null
    receivers:
    - name: default-receiver
      slack_configs:
       - channel: 'aks-alert-demo'
         api_url: 'https://hooks.slack.com/services/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'
         title: zeroaks-alarm-notificatin-demo
         text: This is just a test.
         send_resolved: true
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: default-receiver
      repeat_interval: 3h
